### ISSUE TITLE
Usage Question LED Matrix

### ISSUE THREAD

**Issue by CayenneSF** [pkourany/Adafruit_mfGFX_Library#3]
So, this looks like a nice tool.  Trying to include it in a sketch for driving an LED matrix.  On my initial effort, the installation complains of a lack of "application.h"

Really not sure how I am supposed to use this.  Any clues?

Here are my includes:
# include <Adafruit_GFX.h>   // Core graphics library
# include <RGBmatrixPanel.h> // Hardware-specific library
# include<Adafruit_mfGFX.h>

**Comment by pkourany** [comment]
@CayenneSF, this library was tailored for Particle devices (Core, Photon, Electron).  Their platform uses "application.h" instead of "arduino.h".  I have an [Arduino version](https://github.com/pkourany/Arduino_Adafruit_mfGFX_Library) of the mfGFX library as well.

**Comment by CayenneSF** [comment]
AH!  Thank you.
