### ISSUE TITLE
error

### ISSUE THREAD

**Issue by geva-elettronica** [pkourany/Adafruit_mfGFX_Library#4]
Not Compile.

I copied on the scetch:
Adafruit_mfGFX.cpp
Adafruit_mfGFX.h
fonts.cpp
fonts.h

Removed   //#include "application.h"
Added        #include <stdint.h>

#include <MCUFRIEND_kbv.h>
#define LCD_CS A3 // Chip Select goes to Analog 3
#define LCD_CD A2 // Command/Data goes to Analog 2
#define LCD_WR A1 // LCD Write goes to Analog 1
#define LCD_RD A0 // LCD Read goes to Analog 0
#define LCD_RESET A4 // Can alternately just connect to Arduino's reset pin
#define BLACK   0x0000
#define BLUE    0x001F
#define RED     0xF800
#define GREEN   0x07E0
#define CYAN    0x07FF
#define MAGENTA 0xF81F
#define YELLOW  0xFFE0
#define WHITE   0xFFFF
MCUFRIEND_kbv tft;    // Shield has hard-wired pins
void setup() {
  tft.reset();
  uint16_t identifier = tft.readID();
  tft.begin(identifier);
}
void loop() {}

> Arduino:1.8.1 (Windows 7), Scheda:"Arduino/Genuino Zero (Native USB Port)"
> 
> In file included from sketch\Adafruit_mfGFX.cpp:34:0:
> 
> Adafruit_mfGFX.h:11: error: expected class-name before '{' token
> 
>  class Adafruit_GFX : public Print {
> 
>                                    ^
> 
> Adafruit_mfGFX.h:29: error: 'boolean' has not been declared
> 
>      invertDisplay(boolean i),
> 
>                    ^
> 
> Adafruit_mfGFX.h:56: error: 'boolean' has not been declared
> 
>      setTextWrap(boolean w),
> 
>                  ^
> 
> Adafruit_mfGFX.h:60: error: 'size_t' does not name a type
> 
>    virtual size_t write(uint8_t);
> 
>            ^
> 
> Adafruit_mfGFX.h:87: error: 'boolean' does not name a type
> 
>    boolean
> 
>    ^
> 
> sketch\Adafruit_mfGFX.cpp: In constructor 'Adafruit_GFX::Adafruit_GFX(int16_t, int16_t)':
> 
> Adafruit_mfGFX.cpp:50: error: 'wrap' was not declared in this scope
> 
>    wrap      = true;
> 
>    ^
> 
> sketch\Adafruit_mfGFX.cpp: In member function 'virtual void Adafruit_GFX::drawLine(int16_t, int16_t, int16_t, int16_t, uint16_t)':
> 
> Adafruit_mfGFX.cpp:212: error: 'abs' was not declared in this scope
> 
>    int16_t steep = abs(y1 - y0) > abs(x1 - x0);
> 
>                               ^
> 
> sketch\Adafruit_mfGFX.cpp: At global scope:
> 
> Adafruit_mfGFX.cpp:412: error: 'size_t' does not name a type
> 
>  size_t Adafruit_GFX::write(uint8_t c) {
> 
>  ^
> 
> Adafruit_mfGFX.cpp:507: error: variable or field 'setTextWrap' declared void
> 
>  void Adafruit_GFX::setTextWrap(boolean w) {
> 
>                                 ^
> 
> Adafruit_mfGFX.cpp:507: error: 'boolean' was not declared in this scope
> 
> Adafruit_mfGFX.cpp:540: error: variable or field 'invertDisplay' declared void
> 
>  void Adafruit_GFX::invertDisplay(boolean i) {
> 
>                                   ^
> 
> Adafruit_mfGFX.cpp:540: error: 'boolean' was not declared in this scope
> 
> exit status 1
> expected class-name before '{' token
> 
> Questo report potrebbe essere più ricco di informazioni abilitando l'opzione
> "Mostra un output dettagliato durante la compilazione"
> in "File -> Impostazioni"
>

**Comment by gioreva** [comment]
Project

**Comment by pkourany** [comment]
@gioreva , this library is for Particle devices (Photon, Electron).  You should look at the "true" Arduino mfGFX library I created:

https://github.com/pkourany/Arduino_Adafruit_mfGFX_Library)
